version: '3.8'

services:
  jira-dashboard:
    container_name: jira-dashboard
    hostname: jira-dashboard
    build: ./app
    env_file: .env
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - TZ=Europe/Berlin
    command: flask run
    volumes:
      - ./team.txt:/usr/src/team.txt
    restart: unless-stopped
